version: "3.8"

services:
  docker-app:
    container_name: goa-api
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
    volumes:
      - .:/code
    ports:
      - "8080:${PORT}" # Forward port 8080 on the host OS to the port defined in .env
    env_file:
      - .env
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE-mydb}
    deploy:
      restart_policy:
        condition: on-failure
