// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dic

import (
	"goa-golang/app/controller/userController"
	"goa-golang/app/repository/userRepository"
	"goa-golang/app/service/userService"
	"goa-golang/internal/logger"
	"goa-golang/internal/storage"
)

// Injectors from wire.go:

func initUserService(db *storage.DbStore) userService.UserServiceInterface {
	userRepositoryInterface := userRepository.NewUserRepository(db)
	userServiceInterface := userService.NewUserService(userRepositoryInterface)
	return userServiceInterface
}

func initUserController(us userService.UserServiceInterface, logger2 logger.Logger) userController.UserControllerInterface {
	userControllerInterface := userController.NewUserController(us, logger2)
	return userControllerInterface
}
